# Generated by Django 5.2.5 on 2025-08-27 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Creator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('image', models.ImageField(upload_to='image/')),
                ('bio', models.TextField()),
                ('country', models.CharField(choices=[('Germany', 'Germany'), ('France', 'France'), ('United States Of Amerika', 'United States Of Amerika'), ('Uzbekistan', 'Uzbekistan'), ('Egypt', 'Egypt')])),
                ('add_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('image', models.ImageField(upload_to='image/')),
                ('hashtags', models.TextField()),
                ('video', models.URLField(blank=True, null=True)),
                ('country', models.CharField(choices=[('Germany', 'Germany'), ('France', 'France'), ('United States Of Amerika', 'United States Of Amerika'), ('Uzbekistan', 'Uzbekistan'), ('Egypt', 'Egypt')])),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.creator')),
            ],
        ),
    ]
